title: Repositorio AUR de Israel
email: israel.lopez.developer@gmail.com
description: >-
  Descripción cool de mi sitio.

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
style: dark


include: [_pages]
