title: Repositorio AUR de Israel
email: israel.lopez.developer@gmail.com
description: >-
  Descripción cool de mi sitio.

include: [_pages]

header_pages:
  - index.md

style: hacker

footer: 'Hola tio mierdas'
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

